/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f6',
        'surface-dim': '#f8d2c4',
        'surface-bright': '#fff8f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1ec',
        'surface-container': '#ffe9e2',
        'surface-container-high': '#ffe2d8',
        'surface-container-highest': '#ffdbce',
        'on-surface': '#2a170f',
        'on-surface-variant': '#3f4942',
        'inverse-surface': '#422b22',
        'inverse-on-surface': '#ffede7',
        outline: '#6f7a71',
        'outline-variant': '#bfc9bf',
        'surface-tint': '#1b6b45',
        primary: '#005231',
        'on-primary': '#ffffff',
        'primary-container': '#1b6b45',
        'on-primary-container': '#9be9b9',
        'inverse-primary': '#8ad7a8',
        secondary: '#7e5700',
        'on-secondary': '#ffffff',
        'secondary-container': '#fec564',
        'on-secondary-container': '#765100',
        tertiary: '#484642',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#605e59',
        'on-tertiary-container': '#dcd8d1',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#a5f3c3',
        'primary-fixed-dim': '#8ad7a8',
        'on-primary-fixed': '#002111',
        'on-primary-fixed-variant': '#005231',
        'secondary-fixed': '#ffdeac',
        'secondary-fixed-dim': '#f5bd5d',
        'on-secondary-fixed': '#281900',
        'on-secondary-fixed-variant': '#604100',
        'tertiary-fixed': '#e7e2db',
        'tertiary-fixed-dim': '#cac6bf',
        'on-tertiary-fixed': '#1d1c17',
        'on-tertiary-fixed-variant': '#494742',
        background: '#fff8f6',
        'on-background': '#2a170f',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        body: ['Montserrat', 'sans-serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'label-lg': ['Montserrat', 'sans-serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'section-gap-desktop': '120px',
        'section-gap-mobile': '64px',
        'grid-margin': '24px',
        'grid-gutter': '24px',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'shimmer': 'shimmer 2s linear infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '33%': { transform: 'translateY(-10px) rotate(1deg)' },
          '66%': { transform: 'translateY(5px) rotate(-1deg)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
    },
  },
  plugins: [],
}
